from enum import Enum


class WebhookTrigger(str, Enum):
    CREATE_ACCOUNT = "CREATE_ACCOUNT"
    CREATE_ACTIVITY = "CREATE_ACTIVITY"
    CREATE_DONATION = "CREATE_DONATION"
    CREATE_EVENT_REGISTRATION = "CREATE_EVENT_REGISTRATION"
    CREATE_MEMBERSHIP = "CREATE_MEMBERSHIP"
    CREATE_MERGED_ACCOUNT = "CREATE_MERGED_ACCOUNT"
    CREATE_ORDER = "CREATE_ORDER"
    DELETE_ACCOUNT = "DELETE_ACCOUNT"
    DELETE_ACTIVITY = "DELETE_ACTIVITY"
    DELETE_DONATION = "DELETE_DONATION"
    DELETE_EVENT_REGISTRATION = "DELETE_EVENT_REGISTRATION"
    DELETE_MEMBERSHIP = "DELETE_MEMBERSHIP"
    DELETE_ORDER = "DELETE_ORDER"
    UPDATE_ACCOUNT = "UPDATE_ACCOUNT"
    UPDATE_ACTIVITY = "UPDATE_ACTIVITY"
    UPDATE_DONATION = "UPDATE_DONATION"
    UPDATE_EVENT_REGISTRATION = "UPDATE_EVENT_REGISTRATION"
    UPDATE_MEMBERSHIP = "UPDATE_MEMBERSHIP"
    UPDATE_ORDER = "UPDATE_ORDER"

    def __str__(self) -> str:
        return str(self.value)
